#region

using System.Text;

using NLog;

using ReactiveUI;
using ReactiveUI.SourceGenerators;

using Semver;

using SFP.Models;
using SFP.Models.Injection;

#endregion

namespace SFP_UI.ViewModels;

public partial class MainPageViewModel : ViewModelBase
{
    public static MainPageViewModel? Instance { get; private set; }

    private static readonly StringBuilder OutputBuilder = new();

    [Reactive] public partial bool UpdateNotificationIsOpen { get; set; }

    [Reactive] public partial string UpdateNotificationContent { get; set; } = string.Empty;

    [Reactive] public partial bool ButtonsEnabled { get; set; } = true;

    [Reactive] public partial bool IsInjected { get; set; } = Injector.IsInjected;

    [Reactive] public partial string StartSteamText { get; set; } = Steam.IsSteamRunning ? "Restart Steam" : "Start Steam";
    public string Output
    {
        get;
        private set => this.RaiseAndSetIfChanged(ref field, value);
    } = OutputBuilder.ToString();

    // Commands generated by ReactiveUI.SourceGenerators via the [ReactiveCommand] attribute.
    // These will produce properties named UpdateNotificationViewCommand, InjectCommand, StopInjectCommand, StartSteamCommand.

    [ReactiveCommand]
    private static void UpdateNotificationView(string url) => Utils.OpenUrl(url);

    [ReactiveCommand]
    private static void Inject() => _ = Steam.RunTryInject();

    [ReactiveCommand]
    private static void StopInject() => Injector.StopInjection();

    [ReactiveCommand]
    private static void StartSteam() => _ = Steam.RunRestartSteam();

    public MainPageViewModel()
    {
        Instance = this;
        Injector.InjectionStateChanged -= OnInjectionStateChanged;
        Injector.InjectionStateChanged += OnInjectionStateChanged;
        Steam.SteamStarted -= OnSteamStarted;
        Steam.SteamStarted += OnSteamStarted;
        Steam.SteamStopped -= OnSteamStopped;
        Steam.SteamStopped += OnSteamStopped;
    }

    private void OnSteamStopped(object? o, EventArgs eventArgs)
    {
        StartSteamText = "Start Steam";
    }

    private void OnSteamStarted(object? o, EventArgs eventArgs)
    {
        StartSteamText = "Restart Steam";
    }

    private void OnInjectionStateChanged(object? o, EventArgs eventArgs)
    {
        IsInjected = Injector.IsInjected;
    }

    public static void PrintLine(LogLevel level, string message)
    {
        Print(level, $"{message}\n");
    }

    private static void Print(LogLevel level, string message)
    {
        TrimOutput();
        OutputBuilder.Append($"[{DateTime.Now}][{level}] {message}");
        Instance?.Output = OutputBuilder.ToString();
    }

    private static void TrimOutput()
    {
        const short maxLength = short.MaxValue;
        if (OutputBuilder.Length <= maxLength)
        {
            return;
        }

        var output = OutputBuilder.ToString();
        var firstNewlineIndex = output.IndexOf('\n');
        if (firstNewlineIndex == -1)
        {
            return;
        }
        var firstLine = output[..firstNewlineIndex];
        var lastNewlineIndex = output.IndexOf('\n', maxLength / 2);
        if (lastNewlineIndex == -1)
        {
            return;
        }
        OutputBuilder.Clear();
        OutputBuilder.Append(firstLine);
        OutputBuilder.Append(output.AsSpan(lastNewlineIndex));
    }

    public void ShowUpdateNotification(SemVersion oldVersion, SemVersion newVersion)
    {
        Log.Logger.Info($"There is an update available! Your version: {oldVersion} Latest version: {newVersion}");
        UpdateNotificationContent =
            $"Your version: {oldVersion}{Environment.NewLine}Latest version: {newVersion}";
        UpdateNotificationIsOpen = true;
    }
}